In [1]:
import numpy as np

In [3]:
#넘파이의 array 함수에 list를 넣으면 배열로 변환
ar = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar)
print(type(ar))


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


배열은 리스트와 달리 모든 같은 자료형이다. 접근과 반복문 실행이 빠르다

In [4]:
data = [0,1,2,3,4,5,6,7,8,9]
#벡터화 연산
x = np.array(data)
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
2 * a + b

array([False,  True, False])

In [7]:
a == 2

array([False,  True, False])

In [8]:
(a == 2) & (b > 10)

array([False,  True, False])

In [10]:
#2차원 배열(행렬)
c = np.array([[0,1,2], [3,4,5]]) #2X3 행렬
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
print(f'행 갯수: {len(c)}')

행 갯수:2


In [13]:
print(f'열 갯수: {len(c[0])}')

열 갯수: 3


In [15]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [16]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [17]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


연습 문제 2

다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

이 행렬에서 값 7 을 인덱싱한다.

이 행렬에서 값 14 을 인덱싱한다.

이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [23]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
m[1,2], m[2,-1], m[1,1:3], m[1:3,2], m[:2, 3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

In [24]:
#배열 인덱싱
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [27]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [28]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

연습 문제 3

다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

이 배열에서 3의 배수를 찾아라.

이 배열에서 4로 나누면 1이 남는 수를 찾아라.

이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [35]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x[x%3==0], x[x%4==1], x[(x%3==0) & (x%4==1)]

(array([ 3,  6,  9, 12, 15, 18]), array([ 1,  5,  9, 13, 17]), array([9]))

array([9])