In [9]:
import numpy as np
a = np.array([[3,6,5,4,6,9],[2,5,3,4,6,5],[1,6,4,7,3,3],[3,8,5,5,8,1],[5,9,0,5,2,2]])
a

array([[3, 6, 5, 4, 6, 9],
       [2, 5, 3, 4, 6, 5],
       [1, 6, 4, 7, 3, 3],
       [3, 8, 5, 5, 8, 1],
       [5, 9, 0, 5, 2, 2]])

In [10]:
a.max()


9

In [11]:
a.sum(axis=1)


array([33, 25, 24, 30, 23])

In [12]:

a.max(axis=1)

array([9, 6, 7, 8, 9])

In [13]:
a.mean(axis=0)

array([2.8, 6.8, 3.4, 5. , 5. , 4. ])

In [14]:
a.min(axis=0)

array([1, 5, 0, 4, 2, 1])

In [15]:
b = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
b

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [17]:
j = np.argsort(b[1])
b[:,j]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

[[  1   2   3   4]
 [ 46  71  99 100]
 [ 59  81  90 100]]
